config/routes.rb
GitIssue::Application.routes.draw do
  root :to => 'repos#index'
  get '/about', to: 'repos#index'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/signout', to: 'sessions#destroy'
  post '/issue', to: "issue#slack"

  resource :user

  resources :repos do
    member do
      get :make_default
    end
  end

end

app/models/repo.rb
class Repo < ActiveRecord::Base
  attr_accessible :user_id, :name, :owner, :short_name

  validates :name, :owner, presence: true
  validates :short_name, presence: true, format: {with: /^[a-zA-Z]*$/}
  validates_uniqueness_of :short_name, scope: [:user_id]
  validates_uniqueness_of :name, scope: [:user_id, :owner], message: "for this repo has already been added"
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :token, :default_repo_id, :integration_token

  has_many :repos

  validates :email, :token, presence: true
  validates_uniqueness_of :integration_token, allow_nil: true


  def self.find_by_omniauth(auth)
    user = User.find_by_email(auth["info"]["email"])
    return User.create_with_omniauth(auth) unless user
    user.update_attributes(token: auth["credentials"]["token"])
    return user
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.email = auth["info"]["email"]
      user.token = auth["credentials"]["token"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/issue_controller.rb
require 'net/http'
require 'uri'
require 'json'

class IssueController < ApplicationController
  def slack
    return if params[:user_name]=='slackbot'
    text = params[:text][/[a-zA-Z]*\d+/]
    short_name = text[/[a-zA-Z]+/]
    issue_number = text[/\d+/]

    user = User.find_by_integration_token(params[:token])
    repo = short_name.nil? ? Repo.find(user.default_repo_id) : Repo.find_by_short_name(short_name)
    access_token = user.token
    uri = URI.parse("https://api.github.com/repos/#{repo.owner}/#{repo.name}/issues/#{issue_number}?access_token=#{access_token}")
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = (uri.scheme == "https")
    http.start
    res = http.request(Net::HTTP::Get.new(uri.to_s))

    issue = JSON.parse(res.body)
    number = issue['number']
    title = issue['title']
    url = issue['html_url']

    respond_to do |format|
      msg = {text: url.empty? ? "" : "#{repo.owner} / #{repo.name} \n <#{url}|Issue ##{number} #{title}>"}
      format.json {render json: msg}
    end
  end
end

app/controllers/repos_controller.rb
require 'net/http'
require 'uri'

class ReposController < ApplicationController

  helper_method :repo

  def index
    if(session[:user_id])
      @repos = current_user.repos
      access_token = current_user.token
      uri = URI.parse("https://api.github.com/user/orgs?access_token=#{access_token}")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = (uri.scheme == "https")
      http.start
      res = http.request(Net::HTTP::Get.new(uri.to_s))
      @organizations = JSON.parse(res.body)
      @org_repos = Hash.new
      @organizations.each do |org|
        uri = URI.parse("https://api.github.com/orgs/#{org['login']}/repos?type=member&access_token=#{access_token}")
        http = Net::HTTP.new(uri.host, uri.port)
        http.use_ssl = (uri.scheme == "https")
        http.start
        res = http.request(Net::HTTP::Get.new(uri.to_s))
        @org_repos.merge!({org['login'] => JSON.parse(res.body)})
      end
      uri = URI.parse("https://api.github.com/user/repos?access_token=#{access_token}")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = (uri.scheme == "https")
      http.start
      res = http.request(Net::HTTP::Get.new(uri.to_s))
      @user_repos = JSON.parse(res.body)
    end
  end

  def new
    @repo = current_user.repos.new(params[:repo])
    respond_to do |format|
      format.js
      format.html
    end
  end

  def create
    @repo = current_user.repos.new(params[:repo])
    respond_to do |format|
      @result = @repo.save
      current_user.update_attributes(default_repo_id: @repo.id) if @result && current_user.repos.count <= 1
      @flash_message = {notice: "Repo successfully created"}
      format.js
      format.html
    end
  end

  def edit
    respond_to do |format|
      format.js
      format.html
    end
  end

  def update
    respond_to do |format|
      @result = repo.update_attributes(params[:repo])
      @flash_message = {notice: "Repo successfully updated"}
      format.js
      format.html
    end
  end

  def destroy
    repo.destroy
    current_user.update_attributes(default_repo_id: current_user.repos.first.try(:id)) if current_user.default_repo_id==repo.id
    current_user.update_attributes(default_repo_id: nil) if current_user.repos.count == 0
    redirect_to root_path
  end

  def make_default
    current_user.update_attributes(default_repo_id: params[:id])
    redirect_to root_path
  end

  def repo
    @repo ||= current_user.repos.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def update
    respond_to do |format|
      result = current_user.update_attributes(params[:user])
      @flash_message = result ? {notice: "Token successfully updated"} : {alert: "Token has been used by another user"}
      format.js
      format.html
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  BOOTSTRAP_FLASH_MSG = {
    success: 'alert-success',
    alert: 'alert-danger',
    notice: 'alert-info'
  }

  def bootstrap_class_for(flash_type)
    BOOTSTRAP_FLASH_MSG.fetch(flash_type, flash_type.to_s)
  end

end

app/views/layouts/_flash_message.html.erb
<% flash.each do |key, value| %>
  <div class="alert <%= bootstrap_class_for(key) %>">
    <%= value %>
    <button class="close" data-dismiss="alert"><%= '×'.html_safe %></button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GitIssue</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Git Issue</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="<%= "active" if current_page?(root_path)%>"><a href="/">Home</a></li>
          <li class="<%= "active" if current_page?(about_path)%>"><a href="/about">About</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li >Welcome <%= current_user.name %></li>
            <li><a href="/signout">Sign Out</a></li>
          <% else %>
            <%= link_to "Sign in with Github", "/auth/github" %>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div id="flash-message">
    <%= render partial: 'layouts/flash_message' %>
  </div>
  <%= yield %>
</div>
</body>
</html>

app/views/repos/_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4 class="modal-title" id="repo-modal-label"><%= edit ? "Edit" : "Add" %> Repo</h4>
    </div>
    <%= form_for(repo, remote: true) do |f| %>
      <div class="modal-body">
        <ul id="modal-form-error">
          <% repo.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
        <fieldset>
          <div class="field">
            <%= f.label :owner, class: "col-md-3 control-label" %>
            <%= f.text_field :owner %>
          </div>
          <div class="field">
            <%= f.label :name, class: "col-md-3 control-label" %>
            <%= f.text_field :name %>
          </div>
          <div class="field">
            <%= f.label :short_name, class: "col-md-3 control-label" %>
            <%= f.text_field :short_name %>
          </div>
        </fieldset>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit edit ? "Save" : "Add", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/repos/_new.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4 class="modal-title" id="new-repo-modal-label">Add a Repo</h4>
    </div>
    <%= form_for(repo, remote: true) do |f| %>
      <div class="modal-body">
        <ul id="modal-form-error">
          <% repo.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
        <fieldset>
          <div class="field">
            <%= f.label :owner, class: "col-md-3 control-label" %>
            <%= f.text_field :owner %>
          </div>
          <div class="field">
            <%= f.label :name, class: "col-md-3 control-label" %>
            <%= f.text_field :name %>
          </div>
          <div class="field">
            <%= f.label :short_name, class: "col-md-3 control-label" %>
            <%= f.text_field :short_name %>
          </div>
        </fieldset>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit "Add", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/repos/_row.html.erb
<div class="panel panel-default" id="repos-<%= r.id %>">
  <div class="panel-heading">
    <%= "#{r.short_name}: #{r.owner}/#{r.name} " %>
    <div class="actions pull-right">
      <%= link_to "Edit", edit_repo_path(r), remote: true, class: "btn-sm btn-primary" %>
      <%= link_to 'destroy',  r,  method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-sm btn-danger" %>
      <%= link_to 'make default', make_default_repo_path(r), class: "btn-sm btn-primary" unless current_user.default_repo_id == r.id %>
    </div>
  </div>
</div>

app/views/repos/create.js.erb
<% if @result %>
  $("#repo-modal").modal('hide')
  $("#repos").append("<%= j render partial: 'row', locals: {r: repo} %>")
  $("#repos-<%= repo.id %> .panel-heading").effect( "highlight", 3000)
  $("#<%=j repo.owner %> .<%= repo.name %>").remove()
  $("#flash-message").html("<%= j render partial: 'layouts/flash_message', locals: {flash: @flash_message} %>")
  $('html, body').animate({ scrollTop: 0 }, 'fast')
<% else %>
	$("#repo-modal").html("<%= j render partial: 'modal', locals: {edit: false} %>")
<% end %>

app/views/repos/edit.js.erb
$("#repo-modal").html("<%= j render partial: 'modal', locals: {edit: true} %>")
$('#repo-modal').modal('show')

app/views/repos/index.html.erb
<% if current_user %>
  <div class="row">
    <div class="col-md-12">
      <%= form_for current_user, url: user_path, remote: true do |f|%>
        <fieldset>
          <div class="field">
            <%= f.label "Enter your integration token below:", class: "col-4 control-label" %><br/>
            <p>You can find your token in the integration configuration page from slack</p>
            <p>Make sure your outgoing webhook is posting to http://git-issue-slack-integration.herokuapp.com/issue</p>
            <%= f.text_field :integration_token %>
            <%= f.submit "update token" %>
          </div>
        </fieldset>
      <% end %>

      <div class="panel-group" id="repos">
        <h2>Added Repos</h2>
        <% @repos.each do |r| %>
          <%= render partial: 'row', locals: {r: r} %>
        <% end %>
      </div>

      <p>
        <%= link_to "Add a new repo", new_repo_path, remote: true, class: "btn-sm btn-primary" %> or choose from below
      </p>

      <div class="panel-group" id="org-section">
        <h2>Organizations</h2>
        <% @organizations.each do |org| %>
          <div class="panel panel-default" id="<%= org['login'] %>" >
            <div class="panel-heading" data-toggle="collapse" data-parent="#org-section" data-target="#collapse-<%= org['login'] %>">
              <h4 class="panel-title">
                <a href="#javascript;"><%= org['login'] %></a>
              </h4>
            </div>
            <div id="collapse-<%= org['login'] %>" class="panel-collapse collapse">
              <div class="panel-body">
                <% @org_repos[org['login']].each do |repo| %>
                  <% unless current_user.repos.find_by_owner_and_name(org['login'],repo['name']) %>
                    <div class="panel panel-default <%= repo['name'] %>">
                      <div class="panel-body">
                        <%= repo['name'] %>
                        <div class="action pull-right">
                          <%= link_to "Add", new_repo_url(repo: {owner: org['login'], name: repo['name']}),  remote: true, class: "btn-sm btn-primary" %>
                        </div>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <div class="panel-group" id="<%= @user_repos.first['owner']['login'] %>">
        <h2>User Repos</h2>
        <% @user_repos.each do |repo| %>
          <% unless current_user.repos.find_by_owner_and_name(repo['owner']['login'],repo['name']) %>
            <div class="panel panel-default <%= repo['name'] %>">
              <div class="panel-heading">
                <%= repo['name'] %>
                <div class="action pull-right">
                  <%= link_to "Add", new_repo_url(repo: {owner: repo['owner']['login'], name: repo['name']}),  remote: true, class: "btn-sm btn-primary" %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>

    </div>
  </div>
  <div class="modal fade" id="repo-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
<% else %>
  <%= link_to "Sign in with Github", "/auth/github" %>
<% end %>

app/views/repos/new.js.erb
$("#repo-modal").html("<%= j render partial: 'modal', locals: {edit: false} %>")
$('#repo-modal').modal('show')

app/views/repos/update.js.erb
<% if @result %>
  $("#repo-modal").modal('hide')
  $("#repos-<%= repo.id %>").replaceWith("<%= j render partial: 'row', locals: {r: repo} %>")
  $("#repos-<%= repo.id %> .panel-heading").effect( "highlight", 3000)
  $("#flash-message").html("<%= j render partial: 'layouts/flash_message', locals: {flash: @flash_message} %>")
  $('html, body').animate({ scrollTop: 0 }, 'fast')
<% else %>
  $("#repo-modal").html("<%= j render partial 'modal', locals: {edit: true} %>")
<% end %>

app/views/users/update.js.erb
$("#flash-message").html("<%= j render partial: 'layouts/flash_message', locals: {flash: @flash_message} %>")
$('html, body').animate({ scrollTop: 0 }, 'fast')